# Reload configuration with CTRL + R
bind C-r source-file ~/.tmux.conf

# Resize panes, scroll...
set -g mouse on

# Use vim keys to move between panes
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
set -g detach-on-destroy off

# Address vim mode switching delay (http://superuser.com/a/252717/65504)
set -s escape-time 0

# Increase scrollback buffer size from 2000 to 50000 lines
set -g history-limit 50000

# Increase tmux messages display duration from 750ms to 4s
set -g display-time 4000

# Refresh 'status-left' and 'status-right' more often, from every 15s to 5s
set -g status-interval 5

# (OS X) Fix pbcopy/pbpaste for old tmux versions (pre 2.6)
# set -g default-command "reattach-to-user-namespace -l $SHELL"

# Upgrade $TERM
set -g default-terminal "screen-256color"

# Focus events enabled for terminals that support them
set -g focus-events on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Status bar
set -g @plugin 'o0th/tmux-nova'
set -g @nova-nerdfonts true
set -g @nova-nerdfonts-left 
set -g @nova-nerdfonts-right 
set -g @nova-pane "#I #W"
set -g @nova-rows 0
b_bg="#504945"
seg_a="#a89984 #282828"
seg_b="$b_bg #ddc7a1"
inactive_bg="#32302f"
inactive_fg="#ddc7a1"
active_bg="#d20b0b"
active_fg="#ddc7a1"
set -gw window-status-current-style bold
set -g "@nova-status-style-bg" "$inactive_bg"
set -g "@nova-status-style-fg" "$inactive_fg"
set -g "@nova-status-style-active-bg" "$active_bg"
set -g "@nova-status-style-active-fg" "$active_fg"
set -g "@nova-pane-active-border-style" "#44475a"
set -g "@nova-pane-border-style" "#827d51"
set -g @nova-segment-prefix "#{?client_prefix,PREFIX,}"
set -g @nova-segment-prefix-colors "$seg_b"
set -g @nova-segment-session "#{session_name}"
set -g @nova-segment-session-colors "$seg_a"
set -g @nova-segment-whoami "#(whoami)@#h"
set -g @nova-segment-whoami-colors "$seg_a"
set -g @nova-segments-0-left "session"
set -g @nova-segments-0-right "whoami"


# Popups
bind C-t display-popup \
-d "#{pane_current_path}" \
-w 75% \
-h 75% \
-E "zsh"

# Menu
bind C-d display-menu -T "#[align=centre]Dotfiles" -x C -y C \
".zshrc" z "display-popup -E 'nvim ~/.zshrc'" \
".tmux.conf" t "display-popup -E 'nvim ~/.tmux.conf'" \
"Exit" q ""



# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
